version: '3.8'

services:
  mysql:
    platform: linux/amd64
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'kitra'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
